### ISSUE TITLE
dialout user is GID 20 in the container, while in some host OS's is 18 (permissions error on /dev/ttyUSB0)

### ISSUE THREAD

**Issue by dragonsahead** [felddy/weewx-docker#287]
# 🐛 Summary #

Spent many hours debugging this, and seems that the GID in HASSIO is 18 so when mapping a device to a container it will return permissions error

## To reproduce ##

1) set up HASSIO
2) log in with SSH to the OS, in developer mode so you can run containers in the host OS
3) try to map a device internally, see that you can't use it as HASSIO GID is 18 while the OS needs GID 20

## Expected behavior ##

Either change the GID to 18 (you need to do a custom build), or run with the env var WEEWX_GID = 18 (weird workaround, but works)

(wanted to leave this here in case someone hits the issue)

**Comment by felddy** [comment]
You can use the Docker `user` directives to change the `uid` or `gid` the correct value.   If you're using docker-compose it would look something like:

```yml
services:
  weewx:
    image: ghcr.io/felddy/weewx:5
    user: 1000:18
    volumes:
      - type: bind
        source: ./data
        target: /data
    devices:
      - /dev/ttyUSB0
```

Let me know if that works for you.
